### ISSUE TITLE
[bug] Packaging error after using less

### ISSUE THREAD

**Issue by yifengyoujian** [skywalker512/vue-rsloader#1]
Modify the packages/vue - rsloader/SRC/styleInlineLoader ts code after finish packing

```
warning[css]: Css parsing error
  ┌─ src\App.vue:1:1
  │
1 │ export default "button {\n  width: 100px;\n  height: 100px;\n  background-color: #000;\n  color: #fff;\n  font-size: 20px;\n}\n"
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Unexpected end of file, but expected '{'
```

```ts
import webpack = require('webpack')

const StyleInineLoader: webpack.loader.Loader = function (source) {
  // TODO minify this?
  return source
}

export default StyleInineLoader
```
Duplicate address: https://github.com/yifengyoujian/rspack-vue-error

**Comment by skywalker512** [comment]
@yifengyoujian https://github.com/yifengyoujian/rspack-vue-error 

I cannot open this link, it shows 404. 

Inline CSS only appears in [web components](https://vuejs.org/guide/extras/web-components.html). Have you used it?

**Comment by yifengyoujian** [comment]
Sorry, I didn't make this project open and it was due to my usage of the "style lang=less" syntax. It has now been changed to public.

**Comment by skywalker512** [comment]
The fix has already been made here https://github.com/skywalker512/vue-rsloader/commit/52188d47b4424494e2d795e55ac0f0bc61087688, vue-rsloader version 0.0.9 should work now. 

When I wrote vue-rsloader, rspack was not open source and I didn't realize that the array rule was an [OR relationship](https://github.com/web-infra-dev/rspack/blob/v0.1.1/crates/rspack_core/src/options/module.rs#L40). Rspack should add functional rule in the next version

https://github.com/web-infra-dev/rspack/pull/2291

then vue-rsloader will behave consistently with vue-loader.
